apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
    tier: database
spec:
  # Para utilizacao do AKS, basta ser criado o PVC - https://docs.microsoft.com/pt-br/azure/aks/concepts-storage#volumes
  # storageClassName:  managed-premium
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
