apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-v2
spec:
  type: NodePort
  ports:
  - name: http
    port: 8083
    targetPort: 8080
    nodePort: 30002 
    protocol: TCP
  selector:
    app: petclinic-v2
