apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-v1
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001 
    protocol: TCP
  selector:
    app: petclinic-v1
